### ISSUE TITLE
Screen flashes white, then crashes

### ISSUE THREAD

**Issue by aknight2015** [Rinnegatamante/raider-vita#1]
I made sure to use the following versions:
Tomb Raider 1 v.1.0.42RC1
Tomb Raider 2 v.1.0.50RC1
When I try to run either game the screen flashes white a few times, then crashes.

**Comment by Rinnegatamante** [comment]
Did you extract datafiles.zip like instruction says?
If so, probably is one of your plugins conflicting.

**Comment by aknight2015** [comment]
I downloaded the VPK and Datafiles using Homebrew Browser. I think it's because it's trying to load the FMVs and can't. I can't modify the FMV's as I'm running Debian CLI on a Chromebook. Great work none the less though, also, good to hear from you again.

**Comment by Rinnegatamante** [comment]
If FMVs are not transcoded, they'll just get skipped. Be sure to have extracted THE CONTENT of assets folder in the tombraider1/2 folders and not the folder itself.

**Comment by aknight2015** [comment]
Yeah, that did it. Thanks.
