### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by Just4Link** [Rinnegatamante/raider-vita#10]
is there a way to change the language of tomb raider 2? TR1 is automatically in my language but TR2 in english. the files i have are multilanguage.

**Comment by pmsobrado** [comment]
I just noticed this. Any way of doing it?

**Comment by pmsobrado** [comment]
Hi @Rinnegatamante I've been looking at the code and I was wondering, as far as I can see, is the language only setting for TR1 and not TR2? I think I saw the lang switches inside an IF for TR1 only:

https://github.com/Rinnegatamante/raider-vita/blob/1eced4039eb8b947598b2eb1f0d908ac38824aae/loader/main.c#L3427

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/raider-vita/commit/e09d1f81f81c04578d1e60f634be296c9d8b8fc7
