### ISSUE TITLE
Crashes on T2 1.2 version

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/raider-vita#14]
Latest version crashes on TR2 but is fine on the 1.1 release

Dump file

[psp2core-1707923640-0x00005e25b7-game.bin.psp2dmp.zip](https://github.com/Rinnegatamante/raider-vita/files/14281616/psp2core-1707923640-0x00005e25b7-game.bin.psp2dmp.zip)

**Comment by Rinnegatamante** [comment]
Download data files.
