### ISSUE TITLE
tombraider2 don´t work without tombraider1 folder

### ISSUE THREAD

**Issue by hardlevel** [Rinnegatamante/raider-vita#2]
I wanted to run only tombraider2, after set all the files, when I try to start, it gives me a black screen, only worked when I changed the name of the folder tombrader2 to tombraider1

**Comment by Rinnegatamante** [comment]
I'll fix this for next release.

**Comment by hardlevel** [comment]
do you have any estimative of when the next releade will come out?

**Comment by Rinnegatamante** [comment]
Atm busy with other projects. No ETA.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/raider-vita/releases/tag/v.1.0.2
