### ISSUE TITLE
 not running even with autoplugin uninstalled

### ISSUE THREAD

**Issue by hardlevel** [Rinnegatamante/raider-vita#5]
i tried to run tr2 and received the alert about autoplugin, uninstalled but I still receive the message

forcing users to uninstall this way is really a good choice?

**Comment by AndreDK7** [comment]
> i tried to run tr2 and received the alert about autoplugin, uninstalled but I still receive the message
> 
> forcing users to uninstall this way is really a good choice?

It's not Venão, but unfortunately some people are taking it personally.
